AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'

Resources:

  GetBoxesFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.getBoxes
      Runtime: nodejs20.x
      CodeUri: .
      Events:
        GetBoxesApi:
          Type: Api
          Properties:
            Path: /boxes
            Method: get

  PostBoxesFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.postBoxes
      Runtime: nodejs20.x
      CodeUri: .
      Events:
        PostBoxesApi:
          Type: Api
          Properties:
            Path: /boxes
            Method: post

  PostCustomerFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.postCustomer
      Runtime: nodejs20.x
      CodeUri: .
      Events:
        PostCustomerApi:
          Type: Api
          Properties:
            Path: /customers
            Method: post

  GetCustomerByIdFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.getCustomerById
      Runtime: nodejs20.x
      CodeUri: .
      Events:
        GetCustomerByIdApi:
          Type: Api
          Properties:
            Path: /customer/{id}
            Method: get

  PostOrderFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.postOrder
      Runtime: nodejs20.x
      CodeUri: .
      Events:
        PostOrderApi:
          Type: Api
          Properties:
            Path: /order
            Method: post

  GetOrderByIdFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.getOrderById
      Runtime: nodejs20.x
      CodeUri: .
      Events:
        GetOrderByIdApi:
          Type: Api
          Properties:
            Path: /order/{orderId}
            Method: get

  PostOrderItemsFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.postOrderItems
      Runtime: nodejs20.x
      CodeUri: .
      Events:
        PostOrderItemsApi:
          Type: Api
          Properties:
            Path: /orderItems
            Method: post

  GetOrderItemByIdFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.getOrderItemById
      Runtime: nodejs20.x
      CodeUri: .
      Events:
        GetOrderItemByIdApi:
          Type: Api
          Properties:
            Path: /orderItems/{orderItemId}
            Method: get

  MyVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16

  MySubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref MyVPC
      CidrBlock: 10.0.0.0/24

  MyElasticacheSubnetGroup:
    Type: AWS::ElastiCache::SubnetGroup
    Properties:
      Description: Subnet group for ElastiCache
      SubnetIds:
        - !Ref MySubnet

  MyElasticacheRedis:
    Type: 'AWS::ElastiCache::CacheCluster'
    Properties:
      CacheNodeType: cache.t2.micro
      Engine: redis
      NumCacheNodes: 1
      Port: 6379
      VpcSecurityGroupIds:
        - !GetAtt MySecurityGroup.GroupId
      CacheSubnetGroupName: !Ref MyElasticacheSubnetGroup

  MySecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for Lambda function
      VpcId: !Ref MyVPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 6379
          ToPort: 6379
          CidrIp: 0.0.0.0/0