AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'

Resources:

  # MyVPC:
  #   Type: AWS::EC2::VPC
  #   Properties:
  #     CidrBlock: 10.0.0.0/16

  # MySubnet:
  #   Type: AWS::EC2::Subnet
  #   Properties:
  #     VpcId: !Ref MyVPC
  #     CidrBlock: 10.0.0.0/24

  MyElasticacheSubnetGroup:
    Type: AWS::ElastiCache::SubnetGroup
    Properties:
      Description: Subnet group for ElastiCache
      SubnetIds:
        - subnet-02c217f126c0ce1d5

  MyElasticacheRedis:
    Type: 'AWS::ElastiCache::CacheCluster'
    Properties:
      CacheNodeType: cache.t2.micro
      Engine: redis
      NumCacheNodes: 1
      Port: 6379
      VpcSecurityGroupIds:
        - !GetAtt MySecurityGroup.GroupId
      CacheSubnetGroupName: !Ref MyElasticacheSubnetGroup

  MySecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for Lambda function
      VpcId: vpc-066e6a637e37f2752
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 6379
          ToPort: 6379
          CidrIp: 0.0.0.0/0

  # mjbLambdaRole:
  #   Type: AWS::IAM::Role
  #   Properties:
  #     RoleName: mjbLambdaRole
  #     AssumeRolePolicyDocument:
  #       Version: '2012-10-17'
  #       Statement:
  #         - Effect: Allow
  #           Principal:
  #             Service: lambda.amazonaws.com
  #           Action: sts:AssumeRole
  #     ManagedPolicyArns:
  #       - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
  #       - arn:aws:iam::aws:policy/service-role/AWSLambdaVPCAccessExecutionRole

# Functions

  GetBoxesFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.getBoxes
      Runtime: nodejs20.x
      CodeUri: .
      Environment:
        Variables:
          REDIS_HOST: !GetAtt MyElasticacheRedis.RedisEndpoint.Address
      Events:
        GetBoxesApi:
          Type: Api
          Properties:
            Path: /boxes
            Method: get
      Role: arn:aws:iam::730335528058:role/mjbLambdaRole

  PostBoxesFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.postBoxes
      Runtime: nodejs20.x
      CodeUri: .
      Environment:
        Variables:
          REDIS_HOST: !GetAtt MyElasticacheRedis.RedisEndpoint.Address
      Events:
        PostBoxesApi:
          Type: Api
          Properties:
            Path: /boxes
            Method: post
      Role: arn:aws:iam::730335528058:role/mjbLambdaRole

  PostCustomerFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.postCustomer
      Runtime: nodejs20.x
      CodeUri: .
      Environment:
        Variables:
          REDIS_HOST: !GetAtt MyElasticacheRedis.RedisEndpoint.Address
      Events:
        PostCustomerApi:
          Type: Api
          Properties:
            Path: /customers
            Method: post
      Role: arn:aws:iam::730335528058:role/mjbLambdaRole

  GetCustomerByIdFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.getCustomerById
      Runtime: nodejs20.x
      CodeUri: .
      Environment:
        Variables:
          REDIS_HOST: !GetAtt MyElasticacheRedis.RedisEndpoint.Address
      Events:
        GetCustomerByIdApi:
          Type: Api
          Properties:
            Path: /customer/{id}
            Method: get
      Role: arn:aws:iam::730335528058:role/mjbLambdaRole

  PostOrderFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.postOrder
      Runtime: nodejs20.x
      CodeUri: .
      Environment:
        Variables:
          REDIS_HOST: !GetAtt MyElasticacheRedis.RedisEndpoint.Address
      Events:
        PostOrderApi:
          Type: Api
          Properties:
            Path: /order
            Method: post
      Role: arn:aws:iam::730335528058:role/mjbLambdaRole

  GetOrderByIdFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.getOrderById
      Runtime: nodejs20.x
      CodeUri: .
      Environment:
        Variables:
          REDIS_HOST: !GetAtt MyElasticacheRedis.RedisEndpoint.Address
      Events:
        GetOrderByIdApi:
          Type: Api
          Properties:
            Path: /order/{orderId}
            Method: get
      Role: arn:aws:iam::730335528058:role/mjbLambdaRole

  PostOrderItemsFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.postOrderItems
      Runtime: nodejs20.x
      CodeUri: .
      Environment:
        Variables:
          REDIS_HOST: !GetAtt MyElasticacheRedis.RedisEndpoint.Address
      Events:
        PostOrderItemsApi:
          Type: Api
          Properties:
            Path: /orderItems
            Method: post
      Role: arn:aws:iam::730335528058:role/mjbLambdaRole

  GetOrderItemByIdFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.getOrderItemById
      Runtime: nodejs20.x
      CodeUri: .
      Environment:
        Variables:
          REDIS_HOST: !GetAtt MyElasticacheRedis.RedisEndpoint.Address
      Events:
        GetOrderItemByIdApi:
          Type: Api
          Properties:
            Path: /orderItems/{orderItemId}
            Method: get
      Role: arn:aws:iam::730335528058:role/mjbLambdaRole
